export const SCREENS = {
    BOTTOM_TAB: 'BOTTOM_TAB',
    HOME: 'HOME',
    WISHLIST: 'WISHLIST',
    TRANSACTION: 'TRANSACTION',
    CATEGORY: {
        CATEGORY_LISTING: 'CATEGORY_LISTING',
        SHOP_BY_CATEGORY: 'SHOP_BY_CATEGORY'
    },
    PRODUCT: {
        PRODUCT_LISTING: 'PRODUCT_LISTING',
        PRODUCT_BY_ID: 'PRODUCT_BY_ID'
    }
}

export const SCREEN_ROOT_LIST = {

}